<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    //

    public function getRouteKeyName()
    {
        return "slug"; // TODO: Change the autogenerated stub
    }

            //RelationShip
    public function thread(){

        return $this->hasMany(Thread::class);
    }
}
