<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    //
    protected $guarded =[];
    public function path(){

        return "/threads/{$this->channel->slug}/".$this->id;
    }

    public function getRouteKey()
    {
        return 'title'; // TODO: Change the autogenerated stub
    }

    public function addReply($newReply){

       return $this->replies()->create($newReply);
    }

            //RelationShip
    public function user(){

        return $this->belongsTo(User::class);
    }

    public function replies(){

        return $this->hasMany(Reply::class,'thread_id');
    }

    public function channel(){

        return $this->belongsTo(Channel::class);
    }

}
