<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    //

    public function path(){

        return '/threads/'.$this->id;
    }

    public function getRouteKey()
    {
        return 'title'; // TODO: Change the autogenerated stub
    }

            //RelationShip
    public function users(){

        return $this->belongsTo(User::class);
    }

    public function replies(){

        return $this->hasMany(Reply::class);
    }

}
